#!/bin/sh

sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a Float        state=floating
bspc rule -a Emacs        state=tiled
bspc rule -a qutebrowser  desktop=1

bspc config focused_border_color '#FFFFFF'
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width	 2
bspc config window_gap		 1
