#!/bin/sh

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# My additions
WALLPAPER=$HOME/.config/image/wallpaper
setxkbmap -option "ctrl:nocaps" &
sxhkd &
polybar &
xwallpaper --stretch $WALLPAPER &
exec bspwm
