#!/bin/sh

# From default xinitrc configuration

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# My additions
WALLPAPER=$HOME/.config/image/wallpaper
sxhkd &
polybar &
xwallpaper --stretch $WALLPAPER &
$HOME/.config/scripts/toggle_touchpad &
$HOME/.config/scripts/restore_input &
exec bspwm
