#!/bin/sh
ctr=0

show() {
	while true
	do
		[ "$((ctr%300))" = 0 ] && TIME=$(date +%H:%M)
		[ "$((ctr%100))" = 0 ] && BAT=$(acpi | awk '{print $4}' | tr -d ',')

		echo "$TIME %{X:2400}BAT $BAT"
		ctr=$((ctr+1))
		sleep 0.1
	done
}

show | zelbar -B 0x282828 -F 0xFFFFFF -fn 'Source Code Pro-17'
