#!/bin/sh
path="$1"
mime_type="$(file -Lbi -- "$path")"

if [ ! "$#" = 1 ]
then
	echo 'Usage: open <file_name>' >&2
	exit 1
fi

case "$mime_type" in
	application/pdf*)
		exec zathura -- "$path"
	;;

	image*)
		exec imv -- "$path"
	;;

	audio*)
		exec mpv --player-operation-mode=pseudo-gui -- "$path"
	;;

	video*)
		exec mpv -- "$path"
	;;

	text/html*)
		exec qutebrowser -- "$path"
	;;

	text*)
		exec foot -- nvim -- "$path"
	;;

	*)
	;;
esac
