#!/bin/sh
XINITRC=~/.config/xinitrc/${1:-bspwm}
TTY_NUM=$(tty | cut -c 9-)

unused_display() {
	local d=0
	while true ; do
		[ -e "/tmp/.X$d-lock" -o -S "/tmp/.X11-unix/X$d" ] || break
		d=$(($d + 1))
	done
	echo $d
}

if [ $# -gt 1 ]
then
	echo 'Usage: startx [xinitrc_file]'
	exit 1
fi

exec xinit $XINITRC -- /bin/X :$(unused_display) vt$TTY_NUM
