#!/bin/sh
cmd=${1:-get}

case $cmd in
	get)
		amixer -M sget Master | tail -n1 | awk '{print $4}' | tr -d '[]'
	;;
	up)
		arg=${2:-5%}
		amixer -M set Master unmute
		amixer -M set Master "$arg+"
	;;
	down)
		arg=${2:-5%}
		amixer -M set Master unmute
		amixer -M set Master "$arg-"
	;;
	toggle)
		amixer -M set Master toggle
	;;
esac
